// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVzXOJqP-VoBmxSB7DsAwRax7zISiA4zg',
    appId: '1:775895735274:web:0a52caf9dbb5da58e9b093',
    messagingSenderId: '775895735274',
    projectId: 'login-app-ca7c9',
    authDomain: 'login-app-ca7c9.firebaseapp.com',
    storageBucket: 'login-app-ca7c9.appspot.com',
    measurementId: 'G-PQWH4C9CXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD42b-p1HUoAAR6WRJazgPpQG65S15lGak',
    appId: '1:775895735274:android:c4020c2e26ad4c2fe9b093',
    messagingSenderId: '775895735274',
    projectId: 'login-app-ca7c9',
    storageBucket: 'login-app-ca7c9.appspot.com',
  );
}
